// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2tfPVP5CVeqDZAtuMjzE_tz0K62Gb_LY',
    appId: '1:797516731889:web:4d468fd95ba56058806050',
    messagingSenderId: '797516731889',
    projectId: 'fenua-xlife',
    authDomain: 'fenua-xlife.firebaseapp.com',
    storageBucket: 'fenua-xlife.appspot.com',
    measurementId: 'G-DJG5N590E2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFMx7b-AGOZ0kcRrPOeIVH9XaKu3PAqs',
    appId: '1:797516731889:android:3a9509c9f6fe1403806050',
    messagingSenderId: '797516731889',
    projectId: 'fenua-xlife',
    storageBucket: 'fenua-xlife.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7p7sGen9FNj1dcZ4juLv1GdyK1vJh3GY',
    appId: '1:797516731889:ios:7646461b03b4147d806050',
    messagingSenderId: '797516731889',
    projectId: 'fenua-xlife',
    storageBucket: 'fenua-xlife.appspot.com',
    iosClientId: '797516731889-fqss29lkcg10qmmjsoio695jlpggne7r.apps.googleusercontent.com',
    iosBundleId: 'org.microprogramers.oneLifeAdmin',
  );
}
